version: '3.9'
services:
    keycloak:
        image: quay.io/keycloak/keycloak:21.0.2
        command: ["start-dev"]
        ports:
            - '8080:8080'
        container_name: car_owner_app_postgres
        environment:
            KEYCLOAK_ADMIN: 'admin'
            KEYCLOAK_ADMIN_PASSWORD: 'admin'
